apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-id0j
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-id0j@sha256:3cf931c7475f6caab14c03266ed17c5e2dd8c09af089683536fe5cbc16503e7a
        name: my-nodejs
        resources: {}
status: {}
